In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('job_descriptions.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615940 entries, 0 to 1615939
Data columns (total 23 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Job Id            1615940 non-null  int64
 1   Experience        1615940 non-null  object
 2   Qualifications    1615940 non-null  object
 3   Salary Range      1615940 non-null  object
 4   location          1615940 non-null  object
 5   Country           1615940 non-null  object
 6   latitude          1615940 non-null  float64
 7   longitude         1615940 non-null  float64
 8   Work Type         1615940 non-null  object
 9   Company Size      1615940 non-null  int64
 10  Job Posting Date  1615940 non-null  object
 11  Preference        1615940 non-null  object
 12  Contact Person    1615940 non-null  object
 13  Contact           1615940 non-null  object
 14  Job Title         1615940 non-null  object
 15  Role              1615940 non-null  object
 16  Job Portal        1615940 non-null  object
 17  Job Description   1615940 non-null  object
 18  Benefits          1615940 non-null  object
 19  skills            1615940 non-null  object
 20  Responsibilities  1615940 non-null  object
 21  Company           1615940 non-null  object
 22  Company Profile   1610462 non-null  object
dtypes: float64(2), int64(2), object(19)
memory usage: 283.6+ MB

In [6]:
preferred_columns = ['Job Id','Experience','Qualifications','Salary Range','location','Country','Work Type','Job Title','Role','Job Portal','skills','Company']

In [7]:
df = df[preferred_columns]

In [8]:
df

,Job Id,Experience,Qualifications,Salary Range,location,Country,Work Type,Job Title,Role,Job Portal,skills,Company
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,Intern,Digital Marketing Specialist,Social Media Manager,Snagajob,"Social media platforms (e.g., Facebook, Twitte...",Icahn Enterprises
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,Intern,Web Developer,Frontend Web Developer,Idealist,"HTML, CSS, JavaScript Frontend frameworks (e.g...",PNC Financial Services Group
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",Temporary,Operations Manager,Quality Control Manager,Jobs2Careers,Quality control processes and methodologies St...,United Services Automobile Assn.
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,Full-Time,Network Engineer,Wireless Network Engineer,FlexJobs,Wireless network design and architecture Wi-Fi...,Hess
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,Intern,Event Manager,Conference Manager,Jobs2Careers,Event planning Conference logistics Budget man...,Cairn Energy
...,...,...,...,...,...,...,...,...,...,...,...,...
1615935,134563577088850,0 to 12 Years,B.Tech,$64K-$114K,"Malabo (de jure),",Equatorial Guinea,Full-Time,Mechanical Engineer,Mechanical Design Engineer,ZipRecruiter,"Mechanical engineering CAD software (e.g., Sol...",The Hershey Company
1615936,618604818190827,2 to 14 Years,M.Tech,$62K-$130K,Warsaw,Poland,Intern,IT Manager,IT Director,USAJOBS,Strategic IT planning Leadership and managemen...,EQT
1615937,615471367712200,4 to 15 Years,BCA,$60K-$96K,Ashgabat,Turkmenistan,Part-Time,Mechanical Engineer,Mechanical Design Engineer,Indeed,"Mechanical engineering CAD software (e.g., Sol...",KLA
1615938,804137342023945,5 to 15 Years,BCA,$65K-$103K,Ouagadougou,Burkina Faso,Full-Time,HR Coordinator,Training Coordinator,Stack Overflow Jobs,Training program coordination Training materia...,Mahindra & Mahindra
1615939,404645755314484,1 to 11 Years,BBA,$56K-$109K,Asmara,Eritrea,Part-Time,Event Planner,Wedding Planner,USAJOBS,Wedding planning Venue selection Catering and ...,Ashtead Group

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615940 entries, 0 to 1615939
Data columns (total 12 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   Job Id          1615940 non-null  int64
 1   Experience      1615940 non-null  object
 2   Qualifications  1615940 non-null  object
 3   Salary Range    1615940 non-null  object
 4   location        1615940 non-null  object
 5   Country         1615940 non-null  object
 6   Work Type       1615940 non-null  object
 7   Job Title       1615940 non-null  object
 8   Role            1615940 non-null  object
 9   Job Portal      1615940 non-null  object
 10  skills          1615940 non-null  object
 11  Company         1615940 non-null  object
dtypes: int64(1), object(11)
memory usage: 147.9+ MB

In [12]:
df.isnull().sum()

Job Id            0
Experience        0
Qualifications    0
Salary Range      0
location          0
Country           0
Work Type         0
Job Title         0
Role              0
Job Portal        0
skills            0
Company           0
dtype: int64

In [13]:
df.to_csv('jobs.csv')